# Copyright 2024 Léo de Souza
# SPDX-License-Identifier: Apache-2.0

title: "Blitz: Fischer Chess Clock"

author: Léo de Souza

theme: minima

github_username: ldeso

header_pages:
  - LICENSES/Apache-2.0.md
  - CHANGELOG.md
  - PRIVACY_POLICY.md

defaults:
  - scope:
      path: LICENSES/Apache-2.0.md
    values:
      permalink: /license/
      title: License
  - scope:
      path: CHANGELOG.md
    values:
      permalink: /changelog/
      title: Changelog
  - scope:
      path: PRIVACY_POLICY.md
    values:
      permalink: /privacy-policy/
      title: Privacy Policy

exclude:
  - build.gradle.kts
  - CNAME
  - gradle
  - gradle.properties
  - gradlew
  - gradlew.bat
  - LICENSE
  - metadata
  - settings.gradle.kts
  - src

include:
  - 1.png
  - 2.png
  - Apache-2.0.md
  - en-US
  - ic_launcher.webp
  - images
  - LICENSES
  - main
  - metadata
  - mipmap-xxhdpi
  - phoneScreenshots
  - res
  - src

optional_front_matter:
  remove_originals: true

readme_index:
  remove_originals: true
