# Copyright 2024 LÃ©o de Souza
# SPDX-License-Identifier: Apache-2.0

[versions]
androidGradlePlugin = "8.5.0"
androidxActivity = "1.9.0"
androidxAppcompat = "1.7.0"
androidxComposeBom = "2024.06.00"
androidxLifecycle = "2.8.2"
androidxWindowManager = "1.3.0"
bundletoolGradlePlugin = "0.2.4"
jvmToolchain = "17"
kotlin = "2.0.0"
kotlinxCoroutines = "1.8.1"
ossLicenses = "17.0.1"
ossLicensesPlugin = "0.10.6"

[libraries]
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "androidxActivity" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidxAppcompat" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "androidxComposeBom" }
androidx-compose-foundation = { group = "androidx.compose.foundation", name = "foundation" }
androidx-lifecycle-runtime-compose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "androidxLifecycle" }
androidx-lifecycle-viewmodel-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "androidxLifecycle" }
androidx-window = { group = "androidx.window", name = "window", version.ref = "androidxWindowManager" }
kotlinx-coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "kotlinxCoroutines" }
playservices-osslicenses = { group = "com.google.android.gms", name = "play-services-oss-licenses", version.ref = "ossLicenses" }

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
bundletool = { id = "app.accrescent.tools.bundletool", version.ref = "bundletoolGradlePlugin" }
playservices-osslicenses = { id = "com.google.android.gms.oss-licenses-plugin", version.ref = "ossLicensesPlugin" }
